spring:
  port: 8080
  data:
    mongodb:
      uri: mongodb+srv://pawankumar14662693:Pavan%402005@cluster0.xc3pjzx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: DirectTickets
  security:
    user:
      name: Pavan  # Default username
      password: Pavan@2005  # Default generated password
    # Optionally, configure roles and other security settings for dev profile
    oauth2:
      client:
        registration:
          google:
            client-id: gssrgsrgsrsrhsr
            client-secret: hrshsrhsrh
  cors:
    allowed-origins: "http://localhost:3000, http://localhost:8081,exp://192.168.238.92:8081"  # Allow specific origins
    allowed-methods: "GET, POST, PUT, DELETE"
    allowed-headers: "Authorization, Content-Type, Accept"
api:
  irctc:
    url: https://irctc1.p.rapidapi.com/api/v3/trainBetweenStations
    key: c410dedcadmsh81ce343dafbff94p15844bjsn64e25bf61198
    host: irctc1.p.rapidapi.com