spring:
  security:
    user:
      name: Pavan  # Default username
      password: Pavan@2005  # Default generated password
    # Optionally, configure roles and other security settings for dev profile
    oauth2:
      client:
        registration:
  cors:
    allowed-origins: "http://localhost:3000, http://localhost:3002"  # Allow specific origins
    allowed-methods: "GET, POST, PUT, DELETE"
    allowed-headers: "Authorization, Content-Type, Accept"
api:
  irctc:
    url: https://irctc1.p.rapidapi.com/api/v3/trainBetweenStations
    key: c4f00fe4dcmsh8d534755e3441b1p19e015jsn2aef2c24c556
    host: irctc1.p.rapidapi.com